openapi: 3.0.0
info:
  title: Authentication API
  description: API for handling authentication and cross-tab synchronization
  version: 1.0.0
paths:
  /auth/verify-email:
    post:
      summary: Verify user email with token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Email verification token
              required:
                - token
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: Invalid or expired token
        '404':
          description: User not found
  /auth/refresh:
    post:
      summary: Refresh authentication tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  description: Refresh token
              required:
                - refresh_token
      responses:
        '200':
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  expires_at:
                    type: integer
        '401':
          description: Invalid refresh token
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        email_verified:
          type: boolean
        created_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - email_verified